version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./www:/app
  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./www:/app
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'toor'
      MYSQL_USER: 'democracy'
      MYSQL_PASSWORD: 'alfandi'
      MYSQL_DATABASE: 'democracy'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    profiles: ['database_needed']

volumes:
  mysqldata: {}
